name: Build and Deploy to Github Pages
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository 
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: latest

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Deploy to Github pages
      env:
        CI: true
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        npm run ng -- deploy --repo="https://github.com/chemille/chemille.github.io.git" --base-href=/ --name=chemille --email=ohmotrl@gmail.com

