name: Build and Deploy Script
on:
  push:
    branches: [main]
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository 
      uses: actions/checkout@v3

    - name: Setup Node JS
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Deploy to gh pages
      run: |
        npm chemille.github.io --dir=dist/chemille.github.io
      env:
        CI: true
        GH_TOKEN: ${{ secrets.GH_TOKEN }}